name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - 'etl/**'
      - 'dwh/**'  

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Run start job
        run: echo "${{ github.event.head_commit.message }}"

  get-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed folders
        id: get_changed
        uses: Stockopedia/action-get-changed-files@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true
          format: json

      - name: Print changed folders
        run: echo "Changed folders ${{ steps.get_changed.outputs.changed }}"

  etl:
    if: contains(github.event.head_commit.message, 'etl/')
    runs-on: ubuntu-latest
    steps:
      - name: Run etl job
        run: echo "Running etl job"
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: traveler747/invest_helper_bot:tagname
  dwh:
    if: contains(github.event.head_commit.message, 'dwh/')
    runs-on: ubuntu-latest
    steps:
      - name: Run dwh job
        run: echo "Running dwh job"


