name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - 'etl/**'
      - 'dwh/**'  

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Run start job
        run: echo "${{ github.event.head_commit.message }}"


  etl:
    if: contains(github.event.head_commit.message, 'etl/')
    runs-on: ubuntu-latest
    steps:
      - name: Run etl job
        run: echo "Running etl job"
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: traveler747/invest_helper_bot:tagname
  dwh:
    if: contains(github.event.head_commit.message, 'dwh/')
    runs-on: ubuntu-latest
    steps:
      - name: Run dwh job
        run: echo "Running dwh job"


